# App
APP_NAME = "CreditSim"

# CORS Middleware
ALLOW_METHODS = "*"
ALLOW_HEADERS = "*"
ALLOW_ORIGINS = ["*"]

# Amortization French Calculus
FIRST_PERIOD = 0
MIN_PERIOD_INTEREST_AMOUNT = 0
MIN_CAPITAL_PERIOD_AMORTIZATION_AMOUNT = 0
MONTHS_IN_YEAR = 12
ONE = 1
ZERO = 0

# Scoring Mockup  
MIN_DELAY_TIME = 3
MAX_DELAY_TIME = 3
FAILURE_PROBABILITY = 0.1
SCORING_FAILURE_MESSAGE = "Failure on scoring service"